travis:
  secure:
    BINSTAR_TOKEN: c2A2KYq8AQ1C/zDWNKwZUySriYHzoQp1PejoCBEfA5O9+Yy4YSALBYai4UCEmBgfrKxtFN1YsPAu4XIQ5JrIZQQfW5chhhMFh2QVJrmCvLjST5nIJq5Q9ch2n76pBT/XJRUN8h2kPA8nmgeY8+asmfpYgOCkbnCM84/xQrIE9QVKMb6kLcOOChSDmkw5Vsr2W/Wy6/7hn+wqMjD7UjNBm/T6BM6OhzfNTwzdwPYTJ8biUqEb4wuYYtaWVzGZPAxfbmjNXGFfuZkrLpsS7a+9O9G+iM5yccpXggGm7QYdURxe0Nses9bB/mctAFgZdvMKK9q3Vd/R/+/ra6NlVvUrwX5TzWk2fpl1fslThtqMWmN22owbesgMlthM1z0D9phMI/Mlhpyx4DBzNelyXSr0UFam3dcJOKogqULgBw+wYV1ZhbS1rcI3Lrd/LoaPfrVCFr6ltCCrOB4IDOSHjUUH+I6RGqYCd4Ho1W4KhSsgy3s7u56FncejDeIq9if4stixqfbVLfkT8ce6nXW1gVlwbboLwy2MXOglGkX8X5Y3tJCHXAOZNgGpV1YWHXgQslqn+HjwuV7Ofzg+UmLZkmyUXlzHGPAOCtyRdL6/DXb68q7RTvEPQ+f5cG1Qb4Tsxq9E9w8u0XZt1IHXToUerIE5wN3fxAjZJg+0/Ptpbz7/zV4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
